---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: shared-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nks-block-storage
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: orderer-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nks-block-storage
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ca-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nks-block-storage
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: org1-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nks-block-storage
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: org2-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nks-block-storage
